"""Core modules for the Bitcoin Price Forecasting Portal."""

from .configuration import EngineConfig, render_engine_configuration
from .data_pipeline import fetch_data_from_link, get_default_price_column, normalize_remote_csv_link, standardize_and_load_data
from .forecasting import PyTorchLSTM, evaluate_metrics, run_arima, run_holt_winters, run_lstm, run_model
from .ingestion import (
    get_active_dataframe,
    get_uploader_widget_key,
    handle_remote_link_load,
    handle_uploaded_file,
    initialize_uploader_state,
    pop_upload_notice,
)
from .ui import (
    C_BRIGHT_BLUE,
    C_DEEP_GOLD,
    C_GREEN,
    C_MUTED,
    C_NAVY_SURFACE,
    C_PRIMARY,
    C_RED,
    C_SOFT_GOLD,
    C_VOL_DOWN,
    C_VOL_UP,
    apply_layout,
    configure_page,
    inject_custom_css,
    kpi_row,
    no_data_gate,
    page_header,
    render_sidebar_navigation,
    scroll_to_top,
    section_title,
)
from .visualization import (
    build_candlestick_volume_figure,
    build_decomposition_figure,
    build_forecast_projection_figure,
    build_loader_price_figure,
    build_monthly_seasonality_figure,
    build_return_distribution_figure,
    build_monthly_heatmap_figure,
)

__all__ = [
    "C_BRIGHT_BLUE",
    "C_DEEP_GOLD",
    "C_GREEN",
    "C_MUTED",
    "C_NAVY_SURFACE",
    "C_PRIMARY",
    "C_RED",
    "C_SOFT_GOLD",
    "C_VOL_DOWN",
    "C_VOL_UP",
    "EngineConfig",
    "PyTorchLSTM",
    "apply_layout",
    "build_candlestick_volume_figure",
    "build_decomposition_figure",
    "build_forecast_projection_figure",
    "build_loader_price_figure",
    "build_monthly_seasonality_figure",
    "build_return_distribution_figure",
    "build_monthly_heatmap_figure",
    "configure_page",
    "evaluate_metrics",
    "fetch_data_from_link",
    "get_active_dataframe",
    "get_default_price_column",
    "get_uploader_widget_key",
    "handle_remote_link_load",
    "handle_uploaded_file",
    "initialize_uploader_state",
    "inject_custom_css",
    "kpi_row",
    "no_data_gate",
    "normalize_remote_csv_link",
    "page_header",
    "pop_upload_notice",
    "render_engine_configuration",
    "render_sidebar_navigation",
    "scroll_to_top",
    "run_arima",
    "run_holt_winters",
    "run_lstm",
    "run_model",
    "section_title",
    "standardize_and_load_data",
]
